### ISSUE TITLE
Thru-hole version of PCB

### ISSUE THREAD

**Issue by mlp6** [kjans123/BME590_555_timer#1]
Might be nice to also mock up a thru-hole version of the PCB, with only traces on the "bottom" side of the PCB so that all soldering is done at the end of the leads (not "under" the components on the "top" side.  

If mixing SMT and thru-hole, would put all SMT on the bottom.

**Comment by kjans123** [comment]
Oh, sorry Dr. Palmeri, for some reason GitHub didn't notify me you raised this issue. I am just seeing this now. I'll mock up a PCB with thru-hole only parts and all soldering on underside of the board.
